name: Discord Alerts

on:
  push:
    branches: [ "main" ]  # Dispara em commits diretos na main
  pull_request:
    types: [closed]       # Dispara quando uma PR é fechada (mergeada)

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/main'
    steps:
      - name: Enviar notificação para o Discord
        uses: Ilshidur/action-discord@v1
        with:
          args: "🚀 **Nova atualização no repositório!**\n\n📌 **Branch:** ${{ github.ref }}\n💻 **Autor:** ${{ github.actor }}\n🔗 **Commit:** ${{ github.event.head_commit.message }}\n📄 **Detalhes:** ${{ github.event.head_commit.url }}"
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
