name: Discord Notifications
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Webhook URL
        id: validate
        run: |
          if [[ -z "${{ secrets.DISCORD_WEBHOOK_URL }}" ]]; then
            echo "::error::DISCORD_WEBHOOK_URL is empty"
            exit 1
          fi
          if [[ ! "${{ secrets.DISCORD_WEBHOOK_URL }}" =~ ^https://discord\.com/api/webhooks/ ]]; then
            echo "::error::Invalid Discord webhook format"
            exit 1
          fi

      - name: Send Discord Notification
        if: steps.validate.outcome == 'success'
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "username": "GitHub Bot",
              "content": "🚀 Nova atualização em **${{ github.repository }}**",
              "embeds": [{
                "title": "Detalhes do Commit",
                "description": "[Ver alterações](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})",
                "color": 5814783,
                "fields": [
                  {"name": "Branch", "value": "${{ github.ref }}", "inline": true},
                  {"name": "Autor", "value": "${{ github.actor }}", "inline": true}
                ],
                "footer": {
                  "text": "GitHub Actions • $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
                }
              }]
            }' \
            "${{ secrets.DISCORD_WEBHOOK_URL }}"
