name: Discord Notifications
on:
  push:
    branches: [ "main" ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Basic Notification
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"content":"🚀 Nova atualização em '${{ github.repository }}'\nAutor: '${{ github.actor }}'\nCommit: '${{ github.sha }}'"}' \
            "${{ secrets.DISCORD_WEBHOOK_URL }}"
