name: Discord Notifications
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: appleboy/discord-webhook@master
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            🚀 **Nova atualização no repositório**
            📌 Branch: ${{ github.ref }}
            👤 Autor: ${{ github.actor }}
            🔗 Commit: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
